language: python

install:
  - pip install sphinx sphinx-rtd-theme

script:
  - cd docs
  # Use Sphinx to make the html docs
  - make html
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll
  - ls
  - ls ..
  - pwd
  
# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: docs/_build/html/


#https://amarder.github.io/using-travis-ci-to-build-sphinx-docs/